services:
  # 1. Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: pentanet-db
    restart: always
    environment:
      MYSQL_DATABASE: PentaNet
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql

  # 2. API Spring Boot
  backend:
    build: .
    container_name: pentanet-api
    restart: always
    ports:
      - "9999:9999"
    depends_on:
      db:
        condition: service_started
    environment:
      DB_URL: jdbc:mysql://db:3306/PentaNet?allowPublicKeyRetrieval=true&useSSL=false
      DB_USERNAME: root
      DB_PASSWORD: ''
      JWT_SECRET: PentaNetSuperSecretKey_MustBeAtLeast32BytesLong!!

  # 3. Frontend Web (Nginx)
  web:
    image: nginx:alpine
    container_name: pentanet-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /root/PentaNetWeb:/usr/share/nginx/html

  # 4. Adminer (Gestor de BD)
  adminer:
    image: adminer
    container_name: pentanet-adminer
    restart: always
    ports:
      - "8081:8080"

  # 5. mStream (Tu otra app)
  mstream:
    image: linuxserver/mstream:latest
    container_name: mstream-jaleo
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /root/mstream/config:/config
      - /root/mstream/music:/music

volumes:
  mysql-data:
