spring.application.name=CentrosNetApi

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:PentaNet}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:${MYSQLUSER:${DB_USERNAME:root}}}
spring.datasource.password=${MYSQL_PASSWORD:${MYSQLPASSWORD:${DB_PASSWORD:toor}}}

spring.jpa.hibernate.ddl-auto=validate

server.address=0.0.0.0
server.port=${PORT:9999}

# habilitar/deshabilitar api-docs - swagger-ui
springdoc.api-docs.enabled = true
springdoc.swagger-ui.enabled=true

# definir la ruta de swagger-ui
springdoc.swagger-ui.path=/doc/swagger-ui.html

# ======================
# JWT CONFIG
# ======================
jwt.secret=${JWT_SECRET:PentaNetSuperSecretKey_MustBeAtLeast32BytesLong!!}
jwt.expiration=86400000

#http://localhost:9999/doc/swagger-ui.html


# ======================
# MAIL CONFIG (GMAIL EXAMPLE)
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pabloymanu174@gmail.com
spring.mail.password=yclowwpydolvhvxh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
